[package]
name = "particle-physics"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
glam.workspace = true
bytemuck.workspace = true
