[package]
name = "particles-render"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bevy.workspace = true
bevy_catppuccin.workspace = true
particles-core = { path = "../particles-core" }
bytemuck.workspace = true
